version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sql_edge
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuperStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "master"
      TZ: "UTC"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SuperStrong@Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  sqlserver_data:
